### ISSUE TITLE
Porting to EFM8UB1 MCU ?

### ISSUE THREAD

**Issue by gh-jmg** [FPGA-Computer/TUSB-Blaster#1]
This looks a very cool project, but the TUSB3410 is quite expensive ($6+), and needs a Crystal.
Since you started this, SiLabs have released low cost 1T 8051 USB devices, that may be a better fit ?

I also see here http://ixo-jtag.sourceforge.net/archive/ixo_de_usb_jtag.html
that author started C8051F32x/F34x porting some years back, and those parts are predecessors to the EFM8UB1. (earliest ones were 24MHz SysCLK, 48MHz USB, newer are 48MHz for both CPU & USB)

Mouser shows EFM8UB10F8G-C-QFN20 for **81c 1+**
There are also 8k, 16k choices and QFN20, QFN28 or QSOP24 packages.
The newest EFM8UB1 (2016) also have a boot-loader, allowing simpler firmware updates.

I've been looking to see if the SPI port can be used dynamically for the byte-level ByteBlaster, but this will need some testing on the hand-over details between Bit-Mode and Byte-Mode.
SPI has a 4 byte FIFO and can do 48MHz/(2 \* (SPI0CKR + 1)) bit rates (suggests 12MHz max), so that should manage the bulk transfers of JTAG well.

Software-only JTAG is of course simpler, and could be used for proof of concept work.

**Comment by FPGA-Computer** [comment]
I actually used EFM8UB1F16 chips in here https://github.com/FPGA-Computer/Battery-Analyzer
Just that the project hasn't progressed to the point of working firmware.  Things are in limbo.

A port should be considered as a new project as there are very few things in common with the TUSB3410.  That's why this issue is closed.

There are cheap Altera USB Blaster clones out there.  My original interest in this was for OpenOCD, but they have broken a few things intentionally to keep out Altera clones which also break this firmware.  So no more work on this.

This project is released as is as there are few sources of USB drivers outside of the official source code.
